---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint ./defaults ./handlers ./meta ./tasks
  ansible-lint --exclude .virtualenv
platforms:
  - name: Ubuntu
    image: leolleocompo/ubuntu:18.04
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
