---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: runs mongod in background # noqa 301
      shell:
        cmd: mongod &

    - name: evaluates server status # noqa 301
      shell:
        cmd: "mongo --quiet --eval 'db.runCommand({ serverStatus: 1 }).ok'"
      ignore_errors: yes
      register: status_output

    - name: server runs ok
      assert:
        that:
          - status_output.rc == 0
          - status_output.stdout == '1'
